[book]
authors = ["RogerYoungh"]
language = "zh-CN"
multilingual = false
src = "src"
title = "programming"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/RogerYoungh/cource-programming"
git-repository-icon = "fa-github"
site-url = "/cource-programming/"

[output.html.search]
enable = false